# .github/workflows/ci-cd.yml

name: CI/CD for Donor API

on:
  push:
    branches:
      - main # Jalankan workflow setiap kali ada push ke branch main

jobs:
  # Job untuk testing
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Run tests
        run: go test ./...

  # Job untuk build dan deploy
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: donor-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/donor-api:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Masuk ke direktori proyek di VPS
            cd /lokasi/proyek/anda 

            # Buat file .env dari secret
            echo "${{ secrets.ENV_FILE }}" > .env

            # Ambil image terbaru dari Docker Hub
            docker compose pull app

            # Restart layanan aplikasi dengan image baru
            docker compose up -d --no-deps app

            # Hapus image lama yang tidak terpakai
            docker image prune -f
